name: Build LaTeX document and Update README
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ... [previous steps remain the same] ...

      - name: Update Readme
        run: |
          # Remove existing latest build line if it exists
          sed -i '/^\[Latest PDF Build\]/d' Readme.md
          
          # Add new latest build line at the end of the file
          echo -e "\n[Latest PDF Build](${{ steps.get_artifact_url.outputs.ARTIFACT_URL }})" >> Readme.md
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Readme.md
          git commit -m "Update Readme with latest PDF link"
          git push
