name: Build LaTeX document
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: >-
            -pdf 
            -file-line-error 
            -halt-on-error 
            -interaction=nonstopmode
          extra_system_packages: |
            graphviz
            ghostscript

      - name: Rename output file
        if: success()
        run: |
          mv main.pdf radio-101-latest.pdf

      - name: Upload PDF file as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: radio-101-latest
          path: radio-101-latest.pdf
          retention-days: 90

      - name: Update Readme
        if: success()
        run: |
          # Get the artifact URL
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          # Update the PDF link in Readme.md
          NEW_LINK="[Latest PDF Build]($ARTIFACT_URL)"
          if grep -q "\[Latest PDF Build\]" Readme.md; then
            sed -i 's|\[Latest PDF Build\].*|'"$NEW_LINK"'|' Readme.md
          else
            echo -e "\n$NEW_LINK" >> Readme.md
          fi

      - name: Commit changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Readme.md
          git commit -m "Update Readme with latest PDF link" || echo "No changes to commit"
          git push
